name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]  # Triggers on push to main branch
  workflow_dispatch:      # Allows manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create config file
        run: |
          mkdir -p assets/js/
          echo "const CONFIG = {" > assets/js/config.production.google.js
          echo "    GOOGLE_PLACES_API_KEY: '${{ secrets.GOOGLE_PLACES_API_KEY }}'" >> assets/js/config.production.google.js
          echo "};" >> assets/js/config.production.google.js
          ls -la assets/js/
          cat assets/js/config.production.google.js
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 