name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]  # Trigger on push to main
  workflow_dispatch:    # Allow manual trigger

permissions:
  contents: read        # Read repo contents
  pages: write          # Write to Pages
  id-token: write       # Authenticate with GitHub token

concurrency:
  group: "pages"        # Avoid parallel runs
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1    # Shallow clone for speed

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'         # Use root directory (your static files)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4